services:
  - type: web
    name: mon-app-laravel
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: ma-base-postgres
          property: connectionString

databases:
  - name: ma-base-postgres
    databaseName: laravel_db
    user: laravel_user